#' @import dplyr
#' @import stringr
#' @importFrom utils read.table write.table














# 16 Feb 2026
# IK
# License:  GPL-3.0 


# FUNCTION-3
# This function retains only gene_id, transcript_id, and gene_name attributes in the 9th column of the GTF file
# Recommended to retain only gene_id, transcript_id, and gene_name attributes.
# LINK: https://kb.10xgenomics.com/hc/en-us/articles/4707448154381-Common-mkref-formatting-errors-when-building-custom-reference-from-NCBI-UCSC-or-RefSeq-genomes


# mamba activate 00_R_env
#library(tidyverse)

# Function-3 parameters:
# result  output generated by running FUN-2 (11_process_gtf_FUN2.r) 
# keep = c('gene_id', 'transcript_id', 'gene_name') #### a character vector of length 3

process_attributes_column <- function( result, keep_attributes, out_path, genome_name, genome_version ){   
    # 1.1. Data frame with re-calculated coordinates by process_gtf() function 
    FINAL_df2=result
    keep=keep_attributes
    req_vec <- rep("", times=length(FINAL_df2$attribute))
    # 1.2 Iterate through each row of the 'attribute' column and keep only required by Cell Ranger attributes
    for (numeric in (1:length(FINAL_df2$attribute))){
        # 1.1 Split vector by ';'
        ###split_val = as.vector(unlist(strsplit(  gtf_file[numeric, "attribute"], "; ")))
        ###split_val = strsplit(FINAL_df2$attribute[numeric], "; ")
        split_val = as.vector(unlist(strsplit(  FINAL_df2[numeric, "attribute"], "; ")))
        #print(split_val)
        # 1.2 Subset to matching multiple pattern
        subset_matches <- unique(grep(paste(keep,collapse="|"), split_val, value=TRUE))
        # 1.3 Combine into one vector
        combine_fin=paste(subset_matches[1], subset_matches[2], subset_matches[3], sep="; ")
        #print(combine_fin)
        # 1.4 Remove NAs
        no_NAs = str_remove_all(combine_fin, '; NA')
        #print(no_NAs)
        # 1.5 Add ';' at the end of each value in 'attribute' column
        col9=paste(no_NAs,";",sep="")
        print(col9)
        # 1.6 Populate a vector
        req_vec[numeric]<-col9	
    }
    # 1.3 Replace last column 'attributes' with req_vec
    FINAL_df2$attribute=req_vec

    # 1.4 File name
    output_file <- paste0( out_path, "B1_FINAL_MODIFIED_GTF_", genome_name, "_", genome_version, ".gtf")

    # 1.5 Write out FINAL GTF file with modified attributes column
    write.table(FINAL_df2,
              file = output_file,
              quote = FALSE, row.names = FALSE, col.names = FALSE, sep = "\t")
    return(FINAL_df2)
}
