# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "start", # <process_gtf>
  "RegionStart", # <process_gtf>
  "RegionEnd", # <process_gtf>
  "end", # <process_gtf>
  NULL
))
